# This is a basic workflow to help you get started with Actions

name: Deploy Dev UMGC City Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DEV_WEB_NAME }}
        run: heroku container:login

      - name: Debug
        run: echo ${{ secrets.HEROKU_DEV_WEB_NAME }}

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:push web -a ${{ secrets.HEROKU_DEV_WEB_NAME }} 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:release web -a ${{ secrets.HEROKU_DEV_WEB_NAME }}
