# This is a basic workflow to help you get started with Actions

name: Test/Deploy UMGC City Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Runs a single command using the runners shell
      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run test

      - name: fix code coverage paths
        working-directory: ./coverage
        run: sed -i 's/\/home\/runner\/work\/umgc.city.frontend\/umgc.city.frontend\//\/github\/workspace\//g' lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.CITY_FRONTEND_SONAR }}

  deploy-heroku:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DEV_WEB_NAME }}
        run: |
          echo $HEROKU_APP_NAME
          heroku container:login
        
      - name: Debug
        run: echo ${{ secrets.HEROKU_DEV_WEB_NAME }}
        
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:push web -a ${{ secrets.HEROKU_DEV_WEB_NAME }} 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:release web -a ${{ secrets.HEROKU_APPDEV_NAME }}
